rkwadriga_jwt:
    login_url: rkwadriga_jwt_auth_login
    login_pram: email
    password_param: password
    keys_dir: '%env(string::KEYS_DIR)%'
    private_key_name: private.pem
    public_key_name: public.pem