rkwadriga_jwt:
    login_url: rkwadriga_jwt_auth_login
    login_pram: email
    password_param: password
    secret_key: '%env(string::SECRET_KEY)%'
    encoding_algorithm: SHA256
    access_token_life_time: 3600
    refresh_token_life_time: 15552000
    access_token_location: http_header
    access_token_param_name: Authorization
    refresh_token_location: body
    refresh_token_param_name: refresh_token
    token_type: Bearer