rkwadriga_jwt:
    provider: app_user_provider
    user_identifier: email
    login_url: rkwadriga_jwt_auth_login
    refresh_url: rkwadriga_jwt_refresh_token
    login_pram: email
    password_param: password
    secret_key: '%env(string::RKWADRIGA_JWT_SECRET)%'
    encoding_algorithm: SHA256
    encoding_hashing_count: 3
    access_token_life_time: 3600
    refresh_token_life_time: 15552000
    access_token_location: header
    access_token_param_name: Authorization
    refresh_token_location: body
    refresh_token_param_name: refresh_token
    token_type: Bearer
    refresh_tokens_in_db: true
    refresh_tokens_table: refresh_token
    refresh_tokens_limit: 3
    rewrite_on_limit_exceeded: true