services:
    Rkwadriga\JwtBundle\Service\Config:
        arguments:
            - '@service_container'
        public: false

    Rkwadriga\JwtBundle\Service\PayloadGenerator: ~
    Rkwadriga\JwtBundle\DependencyInjection\PayloadGeneratorInterface:
        alias: Rkwadriga\JwtBundle\Service\PayloadGenerator
        public: true

    Rkwadriga\JwtBundle\Service\HeadGenerator:
        arguments:
            - '@Rkwadriga\JwtBundle\Service\Config'
    Rkwadriga\JwtBundle\DependencyInjection\HeadGeneratorInterface:
        alias: Rkwadriga\JwtBundle\Service\HeadGenerator
        public: true

    Rkwadriga\JwtBundle\Service\Serializer:
        arguments:
            - '@Rkwadriga\JwtBundle\Service\Config'
    Rkwadriga\JwtBundle\DependencyInjection\SerializerInterface:
        alias: Rkwadriga\JwtBundle\Service\Serializer
        public: true

    Rkwadriga\JwtBundle\Service\TokenGenerator:
        arguments:
            - '@Rkwadriga\JwtBundle\Service\Config'
            - '@debug.event_dispatcher'
            - '@Rkwadriga\JwtBundle\DependencyInjection\SerializerInterface'
            - '@Rkwadriga\JwtBundle\DependencyInjection\HeadGeneratorInterface'
    Rkwadriga\JwtBundle\DependencyInjection\TokenGeneratorInterface:
        alias: Rkwadriga\JwtBundle\Service\TokenGenerator
        public: true

    Rkwadriga\JwtBundle\Service\TokenIdentifier:
        arguments:
            - '@Rkwadriga\JwtBundle\Service\Config'
    Rkwadriga\JwtBundle\DependencyInjection\TokenIdentifierInterface:
        alias: Rkwadriga\JwtBundle\Service\TokenIdentifier
        public: true

    Rkwadriga\JwtBundle\Service\TokenResponseCreator: ~
    Rkwadriga\JwtBundle\DependencyInjection\TokenResponseCreatorInterface:
        alias: Rkwadriga\JwtBundle\Service\TokenResponseCreator
        public: true

    Rkwadriga\JwtBundle\Service\TokenValidator:
        arguments:
            - '@Rkwadriga\JwtBundle\Service\Config'
    Rkwadriga\JwtBundle\DependencyInjection\TokenValidatorInterface:
        alias: Rkwadriga\JwtBundle\Service\TokenValidator
        public: true

    Rkwadriga\JwtBundle\Authenticator\JwtAuthenticator:
        arguments:
            - '@Rkwadriga\JwtBundle\Service\Config'
            - '@debug.event_dispatcher'
            - '@rkwadriga.jwt.provider'
            - '@Rkwadriga\JwtBundle\DependencyInjection\TokenIdentifierInterface'
            - '@Rkwadriga\JwtBundle\DependencyInjection\TokenGeneratorInterface'
            - '@Rkwadriga\JwtBundle\DependencyInjection\TokenValidatorInterface'
    rkwadriga.jwt.jws_authenticator:
        alias: Rkwadriga\JwtBundle\Authenticator\JwtAuthenticator
        public: true

    Rkwadriga\JwtBundle\Authenticator\RefreshAuthenticator:
        arguments:
            - '@Rkwadriga\JwtBundle\Service\Config'
            - '@debug.event_dispatcher'
            - '@rkwadriga.jwt.provider'
            - '@Rkwadriga\JwtBundle\DependencyInjection\TokenIdentifierInterface'
            - '@Rkwadriga\JwtBundle\DependencyInjection\PayloadGeneratorInterface'
            - '@Rkwadriga\JwtBundle\DependencyInjection\TokenGeneratorInterface'
            - '@Rkwadriga\JwtBundle\DependencyInjection\TokenValidatorInterface'
            - '@Symfony\Component\Serializer\SerializerInterface'
            - '@Rkwadriga\JwtBundle\DependencyInjection\TokenResponseCreatorInterface'
    rkwadriga.jwt.refresh_authenticator:
        alias: Rkwadriga\JwtBundle\Authenticator\RefreshAuthenticator
        public: true

    Rkwadriga\JwtBundle\Authenticator\LoginAuthenticator:
        arguments:
            - '@Rkwadriga\JwtBundle\Service\Config'
            - '@debug.event_dispatcher'
            - '@rkwadriga.jwt.provider'
            - '@security.password_hasher_factory'
            - '@Symfony\Component\Serializer\SerializerInterface'
            - '@Rkwadriga\JwtBundle\DependencyInjection\PayloadGeneratorInterface'
            - '@Rkwadriga\JwtBundle\DependencyInjection\TokenGeneratorInterface'
            - '@Rkwadriga\JwtBundle\DependencyInjection\TokenResponseCreatorInterface'
    rkwadriga.jwt.login_authenticator:
        alias: Rkwadriga\JwtBundle\Authenticator\LoginAuthenticator
        public: true