services:
    Symfony\Component\DependencyInjection\Container: ~

    Rkwadriga\JwtBundle\Service\Config:
        arguments:
            - '@Symfony\Component\DependencyInjection\Container'
        public: false

    Rkwadriga\JwtBundle\Authenticator\LoginAuthenticator:
        arguments:
            - '@Rkwadriga\JwtBundle\Service\Config'
    rkwadriga.jwt.login_authenticator:
        alias: Rkwadriga\JwtBundle\Authenticator\LoginAuthenticator
        public: true