services:
    Rkwadriga\JwtBundle\DependencyInjection\Services\FileSystem:
        arguments:
            $baseDIr: '%kernel.project_dir%'
    rkwadriga.jws.filesystem_service:
        alias: Rkwadriga\JwtBundle\DependencyInjection\Services\FileSystem
        public: true

    Rkwadriga\JwtBundle\DependencyInjection\Services\KeyGenerator:
        arguments:
            $fileSystem: '@rkwadriga.jws.filesystem_service'
            $keysDir: '%rkwadriga.jwt.keys_dir%'
            $privateKeyName: '%rkwadriga.jwt.private_key_name%'
            $publicKeyName: '%rkwadriga.jwt.public_key_name%'
            $algorithm: '%rkwadriga.jwt.encoding_algorithm%'
            $keyLength: '%rkwadriga.jwt.private_key_length%'
            $keyType: '%rkwadriga.jwt.private_key_type%'
    rkwadriga.jws.key_generator:
        alias: Rkwadriga\JwtBundle\DependencyInjection\Services\KeyGenerator
        public: true

    Rkwadriga\JwtBundle\DependencyInjection\Services\Encoder:
        arguments:
            $keyGenerator: '@rkwadriga.jws.key_generator'
    rkwadriga.jws.encoder:
        alias: Rkwadriga\JwtBundle\DependencyInjection\Services\Encoder
        public: true

    Rkwadriga\JwtBundle\DependencyInjection\Services\TokenGenerator:
        arguments:
            $encoder: '@rkwadriga.jws.encoder'
            $encodingAlgorithm: '%rkwadriga.jwt.encoding_algorithm%'
            $accessTokenLifeTime: '%rkwadriga.jwt.access_token_life_time%'
            $refreshTokenLifeTime: '%rkwadriga.jwt.refresh_token_life_time%'
    rkwadriga.jws.token_generator:
        alias: Rkwadriga\JwtBundle\DependencyInjection\Services\TokenGenerator
        public: true

    Rkwadriga\JwtBundle\DependencyInjection\Security\Authenticators\LoginAuthenticator:
        arguments:
            $tokenGenerator: '@rkwadriga.jws.token_generator'
            $encoder: '@security.password_hasher_factory'
            $serializer: '@Symfony\Component\Serializer\SerializerInterface'
            $userProvider: '@security.user.provider.concrete.app_user_provider'
            $loginUrl: '%rkwadriga.jwt._login_url%'
            $loginParam: '%rkwadriga.jwt.login_pram%'
            $passwordParam: '%rkwadriga.jwt.password_param%'
    rkwadriga.jws.login_authenticator:
        alias: Rkwadriga\JwtBundle\DependencyInjection\Security\Authenticators\LoginAuthenticator
        public: true

    Rkwadriga\JwtBundle\DependencyInjection\Security\Authenticators\JwtAuthenticator: ~
    rkwadriga.jws.jws_authenticator:
        alias: Rkwadriga\JwtBundle\DependencyInjection\Security\Authenticators\JwtAuthenticator
        public: true

    Rkwadriga\JwtBundle\Command\CreateKeyPairCommand: ~