services:
    Rkwadriga\JwtBundle\Service\Config:
        arguments:
            - '@service_container'
        public: false

    Rkwadriga\JwtBundle\Service\PayloadGenerator: ~
    Rkwadriga\JwtBundle\DependencyInjection\PayloadGeneratorInterface:
        alias: Rkwadriga\JwtBundle\Service\PayloadGenerator
        public: true

    Rkwadriga\JwtBundle\Service\HeadGenerator:
        arguments:
            - '@Rkwadriga\JwtBundle\Service\Config'
    Rkwadriga\JwtBundle\DependencyInjection\HeadGeneratorInterface:
        alias: Rkwadriga\JwtBundle\Service\HeadGenerator
        public: true

    Rkwadriga\JwtBundle\Service\Serializer:
        arguments:
            - '@Rkwadriga\JwtBundle\Service\Config'
    Rkwadriga\JwtBundle\DependencyInjection\SerializerInterface:
        alias: Rkwadriga\JwtBundle\Service\Serializer
        public: true

    Rkwadriga\JwtBundle\Service\TokenGenerator:
        arguments:
            - '@Rkwadriga\JwtBundle\Service\Config'
            - '@debug.event_dispatcher'
            - '@Rkwadriga\JwtBundle\DependencyInjection\SerializerInterface'
            - '@Rkwadriga\JwtBundle\DependencyInjection\HeadGeneratorInterface'
    Rkwadriga\JwtBundle\DependencyInjection\TokenGeneratorInterface:
        alias: Rkwadriga\JwtBundle\Service\TokenGenerator
        public: true

    Rkwadriga\JwtBundle\Authenticator\LoginAuthenticator:
        arguments:
            - '@Rkwadriga\JwtBundle\Service\Config'
            - '@debug.event_dispatcher'
            - '@rkwadriga.jwt.provider'
            - '@security.password_hasher_factory'
            - '@Symfony\Component\Serializer\SerializerInterface'
            - '@Rkwadriga\JwtBundle\DependencyInjection\PayloadGeneratorInterface'
            - '@Rkwadriga\JwtBundle\DependencyInjection\TokenGeneratorInterface'
    rkwadriga.jwt.login_authenticator:
        alias: Rkwadriga\JwtBundle\Authenticator\LoginAuthenticator
        public: true