services:
    Rkwadriga\JwtBundle\DependencyInjection\Services\Encoder:
        arguments:
            $algorithm: '%rkwadriga.jwt.encoding_algorithm%'
            $secretKey: '%rkwadriga.jwt.secret_key%'
    rkwadriga.jws.encoder:
        alias: Rkwadriga\JwtBundle\DependencyInjection\Services\Encoder
        public: true

    Rkwadriga\JwtBundle\DependencyInjection\Services\TokenGenerator:
        arguments:
            $encoder: '@rkwadriga.jws.encoder'
            $accessTokenLifeTime: '%rkwadriga.jwt.access_token_life_time%'
            $refreshTokenLifeTime: '%rkwadriga.jwt.refresh_token_life_time%'
    rkwadriga.jws.token_generator:
        alias: Rkwadriga\JwtBundle\DependencyInjection\Services\TokenGenerator
        public: true

    Rkwadriga\JwtBundle\DependencyInjection\Services\TokenIdentifier:
        arguments:
            $encoder: '@rkwadriga.jws.encoder'
            $accessTokenLocation: '%rkwadriga.jwt.access_token_location%'
            $accessTokenParamName: '%rkwadriga.jwt.access_token_param_name%'
            $refreshTokenLocation: '%rkwadriga.jwt.refresh_token_location%'
            $refreshTokenParamName: '%rkwadriga.jwt.refresh_token_location%'
            $tokenType: '%rkwadriga.jwt.token_type%'
    rkwadriga.jws.token_identifier:
        alias: Rkwadriga\JwtBundle\DependencyInjection\Services\TokenIdentifier
        public: true

    Rkwadriga\JwtBundle\DependencyInjection\Services\TokenValidator: ~
    rkwadriga.jws.token_validator:
        alias: Rkwadriga\JwtBundle\DependencyInjection\Services\TokenValidator
        public: true

    Rkwadriga\JwtBundle\DependencyInjection\Security\Authenticators\LoginAuthenticator:
        arguments:
            $tokenGenerator: '@rkwadriga.jws.token_generator'
            $encoder: '@security.password_hasher_factory'
            $serializer: '@Symfony\Component\Serializer\SerializerInterface'
            $userProvider: '@security.user.provider.concrete.app_user_provider'
            $loginUrl: '%rkwadriga.jwt._login_url%'
            $loginParam: '%rkwadriga.jwt.login_pram%'
            $passwordParam: '%rkwadriga.jwt.password_param%'
    rkwadriga.jws.login_authenticator:
        alias: Rkwadriga\JwtBundle\DependencyInjection\Security\Authenticators\LoginAuthenticator
        public: true

    Rkwadriga\JwtBundle\DependencyInjection\Security\Authenticators\JwtAuthenticator:
        arguments:
            $identifier: '@rkwadriga.jws.token_identifier'
            $validator: '@rkwadriga.jws.token_validator'
            $userProvider: '@security.user.provider.concrete.app_user_provider'
            $loginUrl: '%rkwadriga.jwt._login_url%'
            $refreshUrl: '%rkwadriga.jwt.refresh_url%'
            $loginParam: '%rkwadriga.jwt.login_pram%'
    rkwadriga.jws.jws_authenticator:
        alias: Rkwadriga\JwtBundle\DependencyInjection\Security\Authenticators\JwtAuthenticator
        public: true