services:
    rkwadriga.jwt.event_dispatcher:
        class: Symfony\Component\EventDispatcher\EventDispatcher
        public: true

    Rkwadriga\JwtBundle\Repository\RefreshTokenRepository:
        autowire: true
        tags: [ 'doctrine.repository_service' ]

    Rkwadriga\JwtBundle\DependencyInjection\Services\DbService:
        arguments:
            $em: '@doctrine.orm.entity_manager'
            $isEnabled: '%rkwadriga.jwt.refresh_tokens_in_db%'
            $table: '%rkwadriga.jwt.refresh_tokens_table%'
            $tokensLimit: '%rkwadriga.jwt.refresh_tokens_limit%'
            $userIdentifier: '%rkwadriga.jwt.login_pram%'
            $rewriteOnLimitExceeded: '%rkwadriga.jwt.rewrite_on_limit_exceeded%'
    kwadriga.jwt.db_service:
        alias: Rkwadriga\JwtBundle\DependencyInjection\Services\DbService
        public: false

    Rkwadriga\JwtBundle\DependencyInjection\Services\Encoder:
        arguments:
            $algorithm: '%rkwadriga.jwt.encoding_algorithm%'
            $secretKey: '%rkwadriga.jwt.secret_key%'
    rkwadriga.jwt.encoder:
        alias: Rkwadriga\JwtBundle\DependencyInjection\Services\Encoder
        public: true

    Rkwadriga\JwtBundle\DependencyInjection\Services\TokenGenerator:
        arguments:
            $eventsDispatcher: '@rkwadriga.jwt.event_dispatcher'
            $dbService: '@kwadriga.jwt.db_service'
            $encoder: '@rkwadriga.jwt.encoder'
            $accessTokenLifeTime: '%rkwadriga.jwt.access_token_life_time%'
            $refreshTokenLifeTime: '%rkwadriga.jwt.refresh_token_life_time%'
    rkwadriga.jwt.token_generator:
        alias: Rkwadriga\JwtBundle\DependencyInjection\Services\TokenGenerator
        public: true

    Rkwadriga\JwtBundle\DependencyInjection\Services\TokenIdentifier:
        arguments:
            $encoder: '@rkwadriga.jwt.encoder'
            $accessTokenLocation: '%rkwadriga.jwt.access_token_location%'
            $accessTokenParamName: '%rkwadriga.jwt.access_token_param_name%'
            $refreshTokenLocation: '%rkwadriga.jwt.refresh_token_location%'
            $refreshTokenParamName: '%rkwadriga.jwt.refresh_token_param_name%'
            $tokenType: '%rkwadriga.jwt.token_type%'
    rkwadriga.jwt.token_identifier:
        alias: Rkwadriga\JwtBundle\DependencyInjection\Services\TokenIdentifier
        public: true

    Rkwadriga\JwtBundle\DependencyInjection\Services\TokenValidator: ~
    rkwadriga.jwt.token_validator:
        alias: Rkwadriga\JwtBundle\DependencyInjection\Services\TokenValidator
        public: true

    Rkwadriga\JwtBundle\DependencyInjection\Services\TokenRefresher:
        arguments:
            $eventsDispatcher: '@rkwadriga.jwt.event_dispatcher'
            $dbService: '@kwadriga.jwt.db_service'
            $generator: '@rkwadriga.jwt.token_generator'
    rkwadriga.jwt.token_refresher:
        alias: Rkwadriga\JwtBundle\DependencyInjection\Services\TokenRefresher
        public: true

    Rkwadriga\JwtBundle\DependencyInjection\Security\Authenticators\JwtAuthenticator:
        arguments:
            $eventsDispatcher: '@rkwadriga.jwt.event_dispatcher'
            $userProvider: '@rkwadriga.jwt.user_provider'
            $identifier: '@rkwadriga.jwt.token_identifier'
            $validator: '@rkwadriga.jwt.token_validator'
            $loginUrl: '%rkwadriga.jwt.login_url%'
            $refreshUrl: '%rkwadriga.jwt.refresh_url%'
            $loginParam: '%rkwadriga.jwt.login_pram%'
    rkwadriga.jwt.jws_authenticator:
        alias: Rkwadriga\JwtBundle\DependencyInjection\Security\Authenticators\JwtAuthenticator
        public: true

    Rkwadriga\JwtBundle\DependencyInjection\Security\Authenticators\RefreshAuthenticator:
        arguments:
            $eventsDispatcher: '@rkwadriga.jwt.event_dispatcher'
            $userProvider: '@rkwadriga.jwt.user_provider'
            $identifier: '@rkwadriga.jwt.token_identifier'
            $encoder: '@rkwadriga.jwt.encoder'
            $validator: '@rkwadriga.jwt.token_validator'
            $serializer: '@Symfony\Component\Serializer\SerializerInterface'
            $refresher: '@rkwadriga.jwt.token_refresher'
            $refreshUrl: '%rkwadriga.jwt.refresh_url%'
            $loginParam: '%rkwadriga.jwt.login_pram%'
    rkwadriga.jwt.refresh_authenticator:
        alias: Rkwadriga\JwtBundle\DependencyInjection\Security\Authenticators\RefreshAuthenticator
        public: true

    Rkwadriga\JwtBundle\DependencyInjection\Security\Authenticators\LoginAuthenticator:
        arguments:
            $eventsDispatcher: '@rkwadriga.jwt.event_dispatcher'
            $userProvider: '@rkwadriga.jwt.user_provider'
            $encoder: '@security.password_hasher_factory'
            $serializer: '@Symfony\Component\Serializer\SerializerInterface'
            $generator: '@rkwadriga.jwt.token_generator'
            $loginUrl: '%rkwadriga.jwt.login_url%'
            $loginParam: '%rkwadriga.jwt.login_pram%'
            $passwordParam: '%rkwadriga.jwt.password_param%'
    rkwadriga.jwt.login_authenticator:
        alias: Rkwadriga\JwtBundle\DependencyInjection\Security\Authenticators\LoginAuthenticator
        public: true