security:
    firewalls:
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator:
                - rkwadriga.jwt.jws_authenticator
                - rkwadriga.jwt.refresh_authenticator
                - rkwadriga.jwt.login_authenticator
